name: Pylint Check

on: [push, pull_request]

jobs:
  pylint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install pylint

      - name: Run pylint
        id: pylint_check
        run: |
          set -e
          
          # Run pylint on all Python files
          pylint $(find main.py) | tee pylint.log || true  

          # Extract pylint score
          SCORE=$(grep -oE 'rated at [0-9]+.[0-9]+/10' pylint.log | awk '{print $3}' | cut -d'/' -f1 || echo "0")

          if [[ -z "$SCORE" ]]; then
            echo "Error: Could not determine pylint score!"
            cat pylint.log
            exit 1  # Fail the job
          fi

          echo "Pylint score is $SCORE/10"

          # Ignore if score is below 10 (exit successfully)
          if (( $(echo "$SCORE < 10" | bc -l) )); then
            echo "Ignoring pylint score below 10."
            exit 0  # Exit successfully
          fi

      # No need for "Fail job if pylint score is low" because low scores are ignored.
