name: Pylint Check

on: [push, pull_request]

jobs:
  pylint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install pylint

      - name: Run pylint
        id: pylint_check
        run: |
          set -e
          
          pylint main.py | tee pylint.log || true  # Prevent pipeline failure

          SCORE=$(grep -oE 'rated at [0-9]+.[0-9]+/10' pylint.log | awk '{print $3}' | cut -d'/' -f1 || echo "0")

          if [[ -z "$SCORE" ]]; then
            echo "Error: Could not determine pylint score!"
            cat pylint.log
          else
            echo "Pylint score is $SCORE/10"
          fi

          if (( $(echo "$SCORE < 10" | bc -l) )); then
            echo "Warning: Pylint score is below 10/10, but continuing."
          fi
